name: generalROS

on:
  workflow_dispatch:
    inputs:
      software_id:
        description: 'Enter the Software ID'
        required: true
        type: string

jobs:
  generate-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No dependencies to install"

      - name: Run license.py and Save Output
        run: |
          python3 keygen.py  ${{ inputs.software_id }} 1F99C1C4E13A4C8A61897022C6BD83CF0B848D51F1F0B398E52329E5250A502F > ${{ inputs.software_id }}.txt
          cat ${{ inputs.software_id }}.txt  # Display the license in logs for debugging
