name: generalROS

on:
  workflow_dispatch:
    inputs:
      software_id:
        description: 'Enter the Software ID'
        required: true
        type: string

jobs:
  generate-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No dependencies to install"

      - name: Run license.py and Save Output
        run: |
          python3 keygen.py  ${{ inputs.software_id }} 287D418950A7FA860FB121675824B6F255F95F1D2B01EC5FBEF117E7772D4E08 > ${{ inputs.software_id }}.txt
          cat ${{ inputs.software_id }}.txt  # Display the license in logs for debugging
